services:
  - type: web
    name: greety-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main --webhook --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        value: your_actual_token_here
      - key: GROUP_ID
        value: -1002625410129
      - key: ADMIN_ID
        value: 7370661279
      - key: WEBHOOK_SECRET
        generateValue: true
    healthCheckPath: /health
    plan: free
databases:
  - name: greety-db
    plan: free
    databaseName: greety
    user: greety_admin
