services:
  - type: web
    name: greety-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python -m bot.main
    envVars:
      - key: BOT_TOKEN
        value: your_actual_token_here
      - key: GROUP_ID
        value: -1002625410129
      - key: ADMIN_ID
        value: 7370661279
      - key: DATABASE_URL
        fromDatabase:
          name: greety-db
          property: connectionString
    plan: free
